### ISSUE TITLE
选择时间多个选择框的值一样

### ISSUE THREAD

**Issue by xjy2016** [reamd/jQuery-jcDate#1]
当点击第一个时间选择框，不选择时间，然后在点击第二个选择框选择时间，这是选择的事件 是一摸一样的，只能单个点击了就一定要选。

**Comment by xjy2016** [comment]
其实这个也不错了，和jq高版本的兼容了，不过样式里面还是加点box-sizing:content-box;否则会和bootstrap的样式有些冲突

**Comment by daxmeng** [comment]
@xjy2016 谢谢你提的问题，bootstrap的兼容性问题解决了，关于 ``当点击第一个时间选择框，不选择时间，然后在点击第二个选择框选择时间，这是选择的事件 是一摸一样的，只能单个点击了就一定要选。`` 这个问题，我没有明白，可否截个图哈？

**Comment by daxmeng** [comment]
现在终于看懂了，已修复~
